name: MariaDB Backup
version: "2.4.1"
slug: mariadb-backup-zakary
description: Backup MariaDB databases using mariadb-dump
url: https://github.com/Zakary2841/haos_addons/edit/main/mariadbbackup
startup: once
boot: manual
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
host_network: true
privileged: []
map:
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
options:
  DB_HOST: core-mariadb
  DB_USER: homeassistant
  DB_PASS: yourpassword
  DB_BACKUPDIR: /share
  DB_RETENTION_DAYS: 60
  DB_NORMAL_RETENTION_DAYS: 7
  DB_ARCHIVEDIR: Archive
  DB_USE_FOLDERS: true
  DB_FILENAME_FORMAT: "%Y%m%d_%H%M%S"
  DB_INCLUDE_SYSTEM: false
  DB_SEPARATE_FILES: false
schema:
  DB_HOST: str
  DB_USER: str
  DB_PASS: password
  DB_BACKUPDIR: str
  DB_RETENTION_DAYS: int
  DB_NORMAL_RETENTION_DAYS: int
  DB_ARCHIVEDIR: str
  DB_USE_FOLDERS: bool
  DB_FILENAME_FORMAT: str?
  DB_INCLUDE_SYSTEM: bool
  DB_SEPARATE_FILES: bool?
